spring.application.name=UsageAppBackend
app.jwt.secret=myFirstSecretKeyItIs12345678900987654321

spring.datasource.url=jdbc:postgresql://localhost:5432/focusLeague
spring.datasource.username=postgres
spring.datasource.password=sikap

spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true